### ISSUE TITLE
Proposal: Two Matrices  - no tidy then tidy

### ISSUE THREAD

**Issue by glhewett** [cisco/mlspp#388]
I was just looking at the macOS legacy job, and I just noticed that it is a quick job that simply builds... no tidy and no tests.

I would like to propose that we extend the macOS legacy job into a matrix that will include older ubuntu and windows versions that will simply build.  Maybe we can combine the initial ubuntu build and the other legacy builds into that simple matrix.

![MLSPP CI](https://github.com/cisco/mlspp/assets/7768/a5b92675-122d-42dc-808f-16a5e59a0f87)

**Comment by bifurcation** [comment]
I would actually be inclined to do fewer builds, not more.  It seems like we should definitely build and test on the full matrix of platforms and configurations.  But `clang-tidy` is a cross-platform tool that should presumably produce the same results on all platforms, so we probably only need to build with `clang-tidy` on one platform.  So I would propose we do as you propose (no-tidy, then tidy), but limit the tidy to one platform:

1. Check formatting
2. Build + test + interop-test with:
    * Platform: `windows-latest`, `ubuntu-latest`, `macos-latest`, `macos-latest`
    * Crypto libraries: `openssl_1.1`, `openssl_3`, `boringssl`
3. Build on `macos-latest` with old deployment target (no tests)
4. Build with clang-tidy on `ubuntu-latest` (since that's less precious than `macos-latest`)

This might have the pleasant side-effect of getting rid of our macOS hang as well.

**Comment by bifurcation** [comment]
Fixed by some recent PRs.  CI now runs without tidy, then with.
